/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package roulette_client;

import javax.swing.*;
import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;

/**
 *
 * @author Dragan Obradovic
 */
public class ServerSettingsView extends javax.swing.JFrame {

    /**
     * Creates new form ServerSettingsView
     */
    public ServerSettingsView() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        ServerSettingsView = new javax.swing.JPanel();
        ipLabel = new javax.swing.JLabel();
        portLabel = new javax.swing.JLabel();
        ipAddress = new javax.swing.JTextField();
        port = new javax.swing.JTextField();
        confirmButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        ipLabel.setText("IP Address: ");

        portLabel.setText("Port: ");

        confirmButton.setText("Confirm");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ServerInfoInputFrameLayout = new javax.swing.GroupLayout(ServerSettingsView);
        ServerSettingsView.setLayout(ServerInfoInputFrameLayout);
        ServerInfoInputFrameLayout.setHorizontalGroup(
                ServerInfoInputFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ServerInfoInputFrameLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(ServerInfoInputFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(ServerInfoInputFrameLayout.createSequentialGroup()
                                                .addGap(134, 134, 134)
                                                .addComponent(confirmButton))
                                        .addGroup(ServerInfoInputFrameLayout.createSequentialGroup()
                                                .addGroup(ServerInfoInputFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(ipLabel)
                                                        .addComponent(portLabel))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(ServerInfoInputFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(ipAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(port, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ServerInfoInputFrameLayout.setVerticalGroup(
                ServerInfoInputFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ServerInfoInputFrameLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(ServerInfoInputFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(ipLabel)
                                        .addComponent(ipAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(ServerInfoInputFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(portLabel)
                                        .addComponent(port, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(confirmButton)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ServerSettingsView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(ServerSettingsView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    //JA PISAO BEGIN

    void addConfirmButtonListener(ActionListener listenerForConfirmButton){
        confirmButton.addActionListener(listenerForConfirmButton);
    }

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {

    }

    void displayErrorMessage(String errorMessage){
        JOptionPane.showMessageDialog(this, errorMessage);
    }

    public String getIpAddress(){ return ipAddress.getText(); }
    public int getPort() throws NumberFormatException { return Integer.parseInt(port.getText()); }


    //JA PISAO END



    // Variables declaration - do not modify                     
    private javax.swing.JPanel ServerSettingsView;
    private javax.swing.JButton confirmButton;
    private javax.swing.JTextField ipAddress;
    private javax.swing.JLabel ipLabel;
    private javax.swing.JTextField port;
    private javax.swing.JLabel portLabel;
    // End of variables declaration


}
