/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package roulette_server.views;

import javax.swing.*;


public class InitialScreen extends javax.swing.JFrame {

    /**
     * Creates new form start2
     */
    public InitialScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        headerLabel = new javax.swing.JLabel();
        portTextField = new javax.swing.JTextField();
        startingAmountTextField = new javax.swing.JTextField();
        spinningTimeTextField = new javax.swing.JTextField();
        maxPlayerNumberTextField = new javax.swing.JTextField();
        portLabel = new javax.swing.JLabel();
        startingAmountLabel = new javax.swing.JLabel();
        spinningTimeLabel = new javax.swing.JLabel();
        maxPlayersLabel = new javax.swing.JLabel();
        dollarSignLabel = new javax.swing.JLabel();
        secondsLabel = new javax.swing.JLabel();
        playersLabel = new javax.swing.JLabel();
        confirmButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        headerLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        headerLabel.setText("Initial information");

        portTextField.setText("4000");

        startingAmountTextField.setText("200");

        spinningTimeTextField.setText("10");

        maxPlayerNumberTextField.setText("5");

        portLabel.setText("Port:");

        startingAmountLabel.setText("Starting amount:");
        
        spinningTimeLabel.setText("Spinning time:");

        maxPlayersLabel.setText("Max. pleyers:");

        dollarSignLabel.setText("$");

        secondsLabel.setText("seconds");

        playersLabel.setText("players");

        confirmButton.setText("Confirm");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(73, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(headerLabel)
                                                .addGap(127, 127, 127))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(portLabel)
                                                        .addComponent(startingAmountLabel)
                                                        .addComponent(spinningTimeLabel)
                                                        .addComponent(maxPlayersLabel))
                                                .addGap(55, 55, 55)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addComponent(portTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(91, 91, 91))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(startingAmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(dollarSignLabel))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(spinningTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(secondsLabel))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(maxPlayerNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(playersLabel)))
                                                                .addContainerGap())))))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(155, 155, 155)
                                .addComponent(confirmButton)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(maxPlayersLabel)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(headerLabel)
                                                .addGap(39, 39, 39)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(portTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(portLabel))
                                                .addGap(27, 27, 27)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(startingAmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(startingAmountLabel)
                                                        .addComponent(dollarSignLabel))
                                                .addGap(28, 28, 28)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(spinningTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(spinningTimeLabel)
                                                        .addComponent(secondsLabel))
                                                .addGap(26, 26, 26)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(maxPlayerNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(playersLabel))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                .addComponent(confirmButton)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        


    public void addConfirmButtonListener(java.awt.event.ActionListener evt)
    {
        confirmButton.addActionListener(evt);
    }

    public int getPortNumberValue()
    {
        return Integer.parseInt(portTextField.getText());
    }

    public double getStartingAmountValue()
    {
        return Double.parseDouble(startingAmountTextField.getText());

    }

    public int getSpinningTimeValue()
    {
        return Integer.parseInt(spinningTimeTextField.getText());
    }

    public int getMaxPlayerNumberValue()
    {
        return Integer.parseInt(maxPlayerNumberTextField.getText());
    }

    public void displayErrorMessage(String errorMessage)
    {
        JOptionPane.showMessageDialog(this,errorMessage);
    }



    // Variables declaration - do not modify                     
    private javax.swing.JButton confirmButton;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JLabel portLabel;
    private javax.swing.JLabel startingAmountLabel;
    private javax.swing.JLabel spinningTimeLabel;
    private javax.swing.JLabel maxPlayersLabel;
    private javax.swing.JLabel dollarSignLabel;
    private javax.swing.JLabel secondsLabel;
    private javax.swing.JLabel playersLabel;
    private javax.swing.JTextField portTextField;
    private javax.swing.JTextField startingAmountTextField;
    private javax.swing.JTextField spinningTimeTextField;
    private javax.swing.JTextField maxPlayerNumberTextField;
    // End of variables declaration                   
}
