package server.views;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;


public class GameView extends javax.swing.JFrame {

    public GameView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        setResizable(false);
        //initialization of components
        vSeparator = new javax.swing.JSeparator();
        valueTextField = new javax.swing.JTextField();
        colorTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        playersTable = new javax.swing.JTable();
        parityTextField = new javax.swing.JTextField();
        valueLabel = new javax.swing.JLabel();
        parityLabel = new javax.swing.JLabel();
        colorLabel = new javax.swing.JLabel();
        statusBarPanel = new javax.swing.JPanel();
        statusBarLabel = new javax.swing.JLabel();
        statusBarTextField = new javax.swing.JTextField();
        kickButton = new javax.swing.JButton();
        rowTextField = new javax.swing.JTextField();
        rowLabel = new javax.swing.JLabel();
        columnTextField = new javax.swing.JTextField();
        columnLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();


        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Speed Roulette");

        vSeparator.setOrientation(javax.swing.SwingConstants.VERTICAL);



        playersTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                        "ID", "Name", "Balance", "Beted"
                }
        ) {
            boolean[] canEdit = new boolean [] {
                    false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        playersTable.setToolTipText("");
        playersTable.setRowHeight(25);
        jScrollPane1.setViewportView(playersTable);

        //setting up labels
        valueLabel.setText("Value:");
        parityLabel.setText("Parity:");
        colorLabel.setText("Color:");
        rowLabel.setText("Row:");
        columnLabel.setText("Column:");

        //setting up status bar
        statusBarPanel.setBackground(new java.awt.Color(204, 204, 204));

        statusBarLabel.setText("Status:");

        statusBarTextField.setEditable(false);
        statusBarTextField.setBackground(new java.awt.Color(204, 204, 204));
        statusBarTextField.setText("Unidentified");
        statusBarTextField.setBorder(null);


        //disabling field input

        valueTextField.setEnabled(false);
        parityTextField.setEnabled(false);
        colorTextField.setEnabled(false);
        columnTextField.setEnabled(false);
        rowTextField.setEnabled(false);

        //setting disabled text color
        valueTextField.setDisabledTextColor(Color.BLACK);
        parityTextField.setDisabledTextColor(Color.BLACK);
        colorTextField.setDisabledTextColor(Color.BLACK);
        columnTextField.setDisabledTextColor(Color.BLACK);
        rowTextField.setDisabledTextColor(Color.BLACK);

        //setting up field alignment
        valueTextField.setHorizontalAlignment(JTextField.CENTER);
        parityTextField.setHorizontalAlignment(JTextField.CENTER);
        colorTextField.setHorizontalAlignment(JTextField.CENTER);
        columnTextField.setHorizontalAlignment(JTextField.CENTER);
        rowTextField.setHorizontalAlignment(JTextField.CENTER);

        kickButton.setText("Kick");
        jLabel2.setIcon(new javax.swing.ImageIcon("images/wheel.png","roulette")); // NOI18N

        javax.swing.GroupLayout statusBarPanelLayout = new javax.swing.GroupLayout(statusBarPanel);
        statusBarPanel.setLayout(statusBarPanelLayout);
        statusBarPanelLayout.setHorizontalGroup(
                statusBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(statusBarPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(statusBarLabel)
                                .addGap(18, 18, 18)
                                .addComponent(statusBarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        statusBarPanelLayout.setVerticalGroup(
                statusBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(statusBarPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(statusBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(statusBarLabel)
                                        .addComponent(statusBarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(statusBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(parityLabel)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(39, 39, 39)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(valueLabel)
                                                        .addComponent(colorLabel)
                                                        .addComponent(rowLabel)
                                                        .addComponent(columnLabel))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(valueTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(parityTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(colorTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(rowTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(columnTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                                                .addGap(56, 56, 56))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)))
                                .addComponent(vSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(241, 241, 241)
                                                .addComponent(kickButton)))
                                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jLabel2)
                                                .addGap(40, 40, 40)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(valueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(valueLabel))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(parityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(parityLabel))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(colorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(colorLabel))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(rowTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(rowLabel))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(columnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(columnLabel)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(43, 43, 43)
                                                .addComponent(vSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(85, 85, 85)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(kickButton)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(statusBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>                        

    public synchronized void setStatus(String info)
    {
        statusBarTextField.setText(info);
    }

    public synchronized void setFields(int number)
    {
        if(number==-1)
        {
            valueTextField.setText("?");
            parityTextField.setText("?");
            colorTextField.setText("?");
            rowTextField.setText("?");
            columnTextField.setText("?");
        }
        else
        if(number==-2)
        {
            valueTextField.setText("");
            parityTextField.setText("");
            colorTextField.setText("");
            colorTextField.setBackground(Color.white);
            rowTextField.setText("");
            columnTextField.setText("");
        }
        else
        {
            valueTextField.setText(Integer.toString(number));

            //parity
            if(number%2==0)
                parityTextField.setText("Even");
            else
                parityTextField.setText("Odd");

            //emptying color text field
            colorTextField.setText("");

            //color
            if(number==0)
                //colorTextField.setText("Green");
                colorTextField.setBackground(Color.green);
            else
            {
                int color=number%18;
                if(color==0)
                    colorTextField.setBackground(Color.red);

                else
                if(color<=10 && color%2==1)
                 colorTextField.setBackground(Color.red);

                else
                if(color>10 && color%2==0)
                    colorTextField.setBackground(Color.red);

                else
                    colorTextField.setBackground(Color.black);

            }

            //Row
            if(number==0)
                rowTextField.setText("/");
            else
                rowTextField.setText(Integer.toString((int)(Math.ceil(number / 3.0))));

            //Column
            if(number==0)
                columnTextField.setText("/");
            else
            {
                if(number%3==0)
                    columnTextField.setText(Integer.toString(3));
                else
                    columnTextField.setText(Integer.toString(number%3));
            }
        }

    }

    public synchronized void addTableRow(int id, String name, double balance, double betted)
    {
        DefaultTableModel model=(DefaultTableModel) playersTable.getModel();
        model.addRow(new Object[]{id,name,balance,betted});
    }

    public synchronized void addKickButtonListener(java.awt.event.ActionListener evt)
    {
        kickButton.addActionListener(evt);
    }

    public synchronized int removeSelectedRow()
    {
        DefaultTableModel model=(DefaultTableModel) playersTable.getModel();
        int rowNumber=playersTable.getSelectedRow();
        int id=Integer.parseInt(playersTable.getValueAt(rowNumber,0).toString());
        model.removeRow(playersTable.getSelectedRow());
        return id;
    }

    public synchronized void updateBettingMoney(int id, double newAmount)
    {
        int nbOfRows=playersTable.getRowCount();
        for(int i=0;i<nbOfRows;i++)
        {
            if(Integer.parseInt(playersTable.getValueAt(i,0).toString())==id)
            {
                double amount=0;
                amount+=Double.parseDouble(playersTable.getValueAt(i, 3).toString()) + newAmount;
                playersTable.setValueAt(amount,i,3);
                break;
            }
        }
    }

    public synchronized void updateBalanceMoney(int id, double newAmount)
    {
        int nbOfRows=playersTable.getRowCount();
        for(int i=0;i<nbOfRows;i++)
        {
            if(Integer.parseInt(playersTable.getValueAt(i, 0).toString())==id)
            {
                playersTable.setValueAt(newAmount,i,2);
                break;
            }
        }
    }

    public synchronized void removeTableRow(int id)
    {
        DefaultTableModel model=(DefaultTableModel) playersTable.getModel();
        int nbOfRows=playersTable.getRowCount();
        for(int i=0;i<nbOfRows;i++)
        {
            if(Integer.parseInt(playersTable.getValueAt(i,0).toString())==id)
            {
                model.removeRow(i);
                break;
            }
        }
    }

    public synchronized  void cancelBettingMoney(int id)
    {
        int nbOfRows=playersTable.getRowCount();
        for(int i=0;i<nbOfRows;i++)
        {
            if(Integer.parseInt(playersTable.getValueAt(i,0).toString())==id)
            {
                playersTable.setValueAt(0.0,i,3);
                break;
            }
        }
    }


    // Variables declaration - do not modify                     
    private javax.swing.JLabel colorLabel;
    private javax.swing.JTextField colorTextField;
    private javax.swing.JLabel columnLabel;
    private javax.swing.JTextField columnTextField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kickButton;
    private javax.swing.JLabel parityLabel;
    private javax.swing.JTextField parityTextField;
    private javax.swing.JTable playersTable;
    private javax.swing.JLabel rowLabel;
    private javax.swing.JTextField rowTextField;
    private javax.swing.JLabel statusBarLabel;
    private javax.swing.JPanel statusBarPanel;
    private javax.swing.JTextField statusBarTextField;
    private javax.swing.JSeparator vSeparator;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JTextField valueTextField;
    // End of variables declaration                   
}
